<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerZiz9eex\appDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerZiz9eex/appDevDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerZiz9eex.legacy');

    return;
}

if (!\class_exists(appDevDebugProjectContainer::class, false)) {
    \class_alias(\ContainerZiz9eex\appDevDebugProjectContainer::class, appDevDebugProjectContainer::class, false);
}

return new \ContainerZiz9eex\appDevDebugProjectContainer([
    'container.build_hash' => 'Ziz9eex',
    'container.build_id' => 'fb0627c9',
    'container.build_time' => 1622024706,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerZiz9eex');
